server:
  port: 80
spring:
  mvc:
    view:
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tiledb
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml